export const INCREASE_COUNTER = 'INCREMENT_NUMBER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const INCREASE_COUNTER_ASYNC = 'INCREASE_COUNTER_ASYNC';
export const DECREASE_COUNTER_ASYNC = 'DECREASE_COUNTER_ASYNC';

export const INCREMENT_BY_ONE = 'INCREMENT_BY_ONE';
export const INCREMENT_BY_TEN = 'INCREMENT_BY_TEN';
